name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Change this to your main branch name 

jobs:
  clang-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt-get update -y && sudo apt-get install -y clang

    - name: Run Clang Static Analyzer
      run: clang-tidy src/**/*.cpp -- -I./include
