name: Run pytest on Windows for all branches

on:
  push:
    branches:
      - 'main'  # Run on main branch

jobs:
  test:
    runs-on: windows-latest  # Use the latest Windows runner

    strategy:
      matrix:
        python-version: [3.9]  # You can specify multiple Python versions if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest